name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint (flake8)
      run: |
        flake8 app

    - name: Format check (black, isort)
      run: |
        black --check app
        isort --check-only app

    - name: Run tests
      env:
        # lightweight SQLite for CI; your app imports aiosqlite in dev deps
        DATABASE_URL: sqlite:///./test.db
        DEBUG: "true"
        SECRET_KEY: test_secret_key
        BACKEND_CORS_ORIGINS: http://localhost:3000
      run: |
        pytest -q


